package day5.part2;

import java.util.ArrayList;
import java.util.Scanner;

public class Solution {
    private static int[] sizes= { 0, 2, 2, 0, 1, 2, 2, 2, 2 };
    private static ArrayList<Integer> result = new ArrayList<>();

    /**
     * Main method of class.
     * @param args
     */
    public static void main(String[] args) {
        //retrieve and parse the input to array of strings
        Scanner scanner = new Scanner(Solution.class.getResourceAsStream("/day5/input5.txt"));
        String[] stringcode = scanner.nextLine().split(",");

        //parse into array of Integers
        Integer[] intcode = new Integer[stringcode.length];
        for (int i = 0; i < intcode.length; i++) {
            intcode[i] = Integer.parseInt(stringcode[i]);
        }
        //set the initial value and solve
        int input = 5;
        solve(intcode, input);
    }

    /**
     * Method to solve the problem
     * @param intcode = array of integers, the input code
     * @param input = initializing value for instruction 3
     * @return - the value outputed by instruction 4
     */
    static int solve(Integer[] intcode, int input){
        //initialize pointer with 0 and loop over the input instructions
        int i = 0;
        while (i < intcode.length) {
            Instruction command = new Instruction(intcode[i], intcode, sizes, result, input);
            i++;
            i = command.execute(i);
        }
        return getResult();
    }

    /**
     * Method to pass the return value
     * @return - the result generated by instruction 4
     */
    public static int getResult() {
        return result.get(0);
    }
}
