package year2019.day9;

import java.util.ArrayList;
import java.util.LinkedList;
import java.util.Scanner;

public class Util {
    static int[] sizes= { 0, 3, 3, 1, 1, 2, 2, 3, 3, 1 };
    private static ArrayList<Long> result;
    static int relativeBase = 0;

    /**
     * Main method of class.
     */
    static long[] parseInput() {
        //retrieve and parse the input to array of strings
        Scanner scanner = new Scanner(Util.class.getResourceAsStream("input9.txt"));
        String[] stringcode = scanner.nextLine().split(",");

        //parse into array of longs
        long[] intcode = new long[stringcode.length];
        for (int i = 0; i < intcode.length; i++) {
            intcode[i] = Long.parseLong(stringcode[i]);
        }
        //set the initial value and solve
        return intcode;
    }

    /**
     * Method to solve the problem
     * @param intcode = array of longs, the input code
     * @param input = initializing value for instruction 3
     * @return - the value outputed by instruction 4
     */
    static ResultTuple solve(long[] intcode, LinkedList<Long> input){
        //initialize pointer with 0 and loop over the input instructions
        ResultTuple result = new ResultTuple();
        int i = 0;
        while (i < intcode.length) {
            Instruction command = new Instruction(intcode[i], intcode, result, input, relativeBase);
            i++;
            i = command.execute(i);
            relativeBase += command.getUpdateValue();
            intcode = command.intcode;
        }
        return result;
    }

    /**
     * Method to pass the return value
     * @return - the result generated by instruction 4
     */
    public static long getResult() {
        return result.get(0);
    }

}
